#!/usr/bin/env php
<?php

$kahlan = 'https://raw.githubusercontent.com/crysalead/kahlan/master/composer.json';
$version = preg_replace('/[^\d\.]+/', '', json_decode(file_get_contents($kahlan), true)['require']['crysalead/dir']);

`COMPOSER_ROOT_VERSION={$version} composer install`;
